name: Cypress E2E Tests
on:  
    pull_request:
        branches:
            - main
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository        
        uses: actions/checkout@v2
      - name: Setup VPN
        env:
          VPN_LOGIN: ${{ secrets.VPN_LOGIN }}
          VPN_PASS: ${{ secrets.VPN_PASS }}
        run: |
            sudo apt install -y wget 
            wget https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3_all.deb
            sudo apt install ./protonvpn-stable-release_1.0.3_all.deb
            sudo apt update
            sudo apt install -y protonvpn-cli
            sudo apt install expect
            expect loginVPNscript
            protonvpn-cli c --cc JP
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      - name: Run Cypress tests
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          DOCKER_DEFAULT_PLATFORM: linux/amd64
          NETWORK_NAME: ${{ secrets.NETWORK_NAME }}
          SECRET_WORDS: ${{ secrets.SECRET_WORDS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            set +e
            docker-compose --env-file ./docker.config up --build --exit-code-from synpress
            export TESTS_EXIT_CODE="$?"
        continue-on-error: true
      - name: Archive artifacts        
        if: always()
        uses: actions/upload-artifact@v3
        with:  
            name: cypress-results
            path: /__w/test-task-red/test-task-red/cypress/videos/ScenarionTests.cy.js.mp4
      - name: Archive artifacts
        if: always()        
        uses: actions/upload-artifact@v3
        with:          
            name: allure-report
            path: ./allure-report/
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
            name: cypress-results
      - name: Decide fail pull request or not
        run:
          exit TESTS_EXIT_CODE
