name: Cypress E2E Tests
on:  
    pull_request:
        branches:
            - main
jobs:
  test:
      runs-on: ubuntu-latest
      container:
        image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      steps:
      - name: Checkout repository        
        uses: actions/checkout@v2
      - name: Set up Node.js  
        uses: actions/setup-node@v3
        with:          
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        env:
          NETWORK_NAME: ${{ secrets.NETWORK_NAME }}
          SECRET_WORDS: ${{ secrets.SECRET_WORDS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
            set +e
            npm run sy:regression
            export TESTS_EXIT_CODE="$?"
        continue-on-error: true
      - name: Archive artifacts        
        if: always()
        uses: actions/upload-artifact@v3
        with:  
            name: cypress-results
            path: /__w/test-task-red/test-task-red/cypress/videos/ScenarionTests.cy.js.mp4
      - name: Archive artifacts
        if: always()        
        uses: actions/upload-artifact@v3
        with:          
            name: allure-report
            path: ./allure-report/
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
            name: cypress-results
      - name: Decide fail pull request or not
        run:
          exit TESTS_EXIT_CODE
